import { Inter, Agbalumo } from 'next/font/google'
import Navbar from '@components/Navbar'
import SessionAuthProvider from '@hooks/SessionAuthProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const agbalumo = Agbalumo({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-agbalumo'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <SessionAuthProvider>
        <body className={`${inter.className} ${agbalumo.variable}`}>
          <Navbar />
          {children}
        </body>
      </SessionAuthProvider>
    </html>
  )
}
